spring.application.name=demo

# Configuração Dinâmica para a Nuvem (Supabase)
spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Limite de conexões OBRIGATÓRIO para não estourar a cota do Supabase (plano gratuito)
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

# O Hibernate vai atualizar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update  
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-super-segura}